### ISSUE TITLE
Compatibility problems on Linux

### ISSUE THREAD

**Issue by lordfeck** [jdah/microcraft#1]
Greetings,

I've tried running the jarfile on both Debian and Void Linux. Unfortunately, in either case, I get a similar error on startup:

````
$ java -jar Microcraft_10.jar 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/jdh/microcraft/Main has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0
````

On Void at least, my Java version is:

````
$ java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b02)
````

I might have better luck compiling the source myself, but I thought I should raise the issue nonetheless.

**Comment by jdah** [comment]
Hey there,

This isn't actually a compatibility issue, you just have an outdated JRE. You'll need to upgrade to the latest (Java 14+) to run things. I would give instructions, but they'll vary depending on your selected flavor of Linux. I'll note this in the documentation.
