### ISSUE TITLE
Breaking chest doesn't drop items

### ISSUE THREAD

**Issue by JakeMalis** [jdah/microcraft#4]
I put some items into a chest, and then when I broke the chest the items didn't break. Not sure if that is intentional, but it may be a bug.

**Comment by SummeryLavaRain** [comment]
I don't think he ever implemented it in the game as a mechanic￼.

**Comment by myriath** [comment]
It seems as though this is supposed to happen, as this code seems to try to do that, the issue is it's in the `hit()` method instead of the `onHit()` method, so it never gets called as the chest can't hit something (At least I don't think it can).
```
// EntityChest.java
@Override
    public boolean hit(Entity e) {
        if (super.hit(e)) {
            for (ItemStack s : this.inventory.stacks) {
                EntityItem.spawn(this.level, s, Level.toCenter(e.tileX), Level.toCenter(e.tileY));
            }
            return true;
        }
        return false;
    }
```

A potential fix could be Overriding the `getDrops()` method (which gets called when the furniture item is hit) to also return all of the items inside the chest instead of just the chest item itself.

```
// EntityFurniture.java
protected List<ItemStack> getDrops() {
        return List.of(new ItemStack(new ItemInstance(this.item)));
    }
```
```
// EntityChest.java 
@Override
    protected List<ItemStack> getDrops() {
        List<ItemStack> temp = this.inventory.stacks;
        temp.addAll(super.getDrops());
        return temp;
    }
```

**Comment by steviegt6** [comment]
> 
> 
> It seems as though this is supposed to happen, as this code seems to try to do that, the issue is it's in the `hit()` method instead of the `onHit()` method, so it never gets called as the chest can't hit something (At least I don't think it can).
> 
> ```
> // EntityChest.java
> @Override
>     public boolean hit(Entity e) {
>         if (super.hit(e)) {
>             for (ItemStack s : this.inventory.stacks) {
>                 EntityItem.spawn(this.level, s, Level.toCenter(e.tileX), Level.toCenter(e.tileY));
>             }
>             return true;
>         }
>         return false;
>     }
> ```
> 
> A potential fix could be Overriding the `getDrops()` method (which gets called when the furniture item is hit) to also return all of the items inside the chest instead of just the chest item itself.
> 
> ```
> // EntityFurniture.java
> protected List<ItemStack> getDrops() {
>         return List.of(new ItemStack(new ItemInstance(this.item)));
>     }
> ```
> 
> ```
> // EntityChest.java 
> @Override
>     protected List<ItemStack> getDrops() {
>         List<ItemStack> temp = this.inventory.stacks;
>         temp.addAll(super.getDrops());
>         return temp;
>     }
> ```

Can confirm that this is a valid solution.
![WorkingChestDrops](https://user-images.githubusercontent.com/27323911/116158456-3f4ea000-a6de-11eb-8ce2-9a45e65bee3b.gif)

**Comment by JakeMalis** [comment]
@Steviegt6 yes that works, thanks for the info!
