### ISSUE TITLE
won't open??

### ISSUE THREAD

**Issue by SadSushiBar-c** [jdah/microcraft#6]
hi there! i ran the "Microcraft_10.exe" and the setup ran fine however nothing else happens :( i can't open the game and can't find the game through file explorer to try and run

**Comment by jdah** [comment]
Check under `C:\Program Files` or `C:\Program Files (x86)` for the MICROCRAFT folder :)

**Comment by SadSushiBar-c** [comment]
oh i found it! at first i couldn't find it in Program Files x86 so i went to the regular program files and it was there, also i love all the videos so far i really look forward to seeing more! :)
