### ISSUE TITLE
Couldn't build project on Macbook

### ISSUE THREAD

**Issue by Monsterray** [jdah/microcraft#8]
I tried building the game with the package.sh file and got some errors with Java. I have a paste at pastebin [here](https://pastebin.com/SrR6R0tK).

**Comment by red-socks294** [comment]
I think you might have not installed [Java](https://java.com)

**Comment by Monsterray** [comment]
I do have Java installed and it looks like version 1.8.

`$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)`

**Comment by jdah** [comment]
It mentions in the README that you need at least Java 14 to build and run. Closing this.
